apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-shipping
  namespace: app
  labels:
    app: oms-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-shipping
  template:
    metadata:
      labels:
        app: oms-shipping
    spec:
      containers:
      - name: oms-shipping
        image: manishsrivastavaggn/oms-shipping:changeMePlease
        ports:
        - containerPort: 8080
   