apiVersion: v1
kind: Service
metadata:
  name: oms-shipping-svc
  namespace: order-domain
  labels:
    app: oms-shipping
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: oms-shipping

